name: Issue
on:
  push:
  issues:
    types: [labeled, closed]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue Number'
        required: true
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: |
          echo "$GITHUB_CONTEXT"
