name: Issue
on:
  push:

jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          g++ -o example example.cpp
          ./example
