name: Issue
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-22.04
    steps:
      - name: Store Pull Request number to artifact
        if: github.event_name == 'pull_request'
        run: |
          mkdir install
          echo "PR_NUMBER=${{ github.event.number }}" > install/pr_number.txt

      - name: Upload install directory
        uses: actions/upload-artifact@v4
        with:
          name: install
          path: install

      - name: Exit code test
        id: exit_code_test
        run: |
          g++ -o example example.cpp | tee xxx.txt
          echo "exit_code_1=${PIPESTATUS[0]}" >> $GITHUB_OUTPUT

          g++ -o example2 example2.cpp | tee yyy.txt
          echo "exit_code_2=${PIPESTATUS[0]}" >> $GITHUB_OUTPUT

      - name: Print exit codes
        run: |
          echo "Exit code 1: ${{ steps.exit_code_test.outputs.exit_code_1 }}"
          echo "Exit code 2: ${{ steps.exit_code_test.outputs.exit_code_2 }}"
